version: '3.2'

services:

  webserver:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./files/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./code/example/web:/var/www

  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./code/example/web:/var/www
    expose:
      - 9000
